Exercise 1: Introduction to Data Analysis

Today, we are surrounded by data. Every time we click a link, buy something online, or use a phone app, we create digital information. But raw data by itself is just a giant, messy pile of numbers. Data analysis is the process of cleaning, organizing, and studying that information to find meaningful patterns and make smart decisions. It usually follows a simple journey. First, you scrub the data to fix mistakes and remove duplicates. Next, you use software or formulas to find trends. And finally, you turn those results into clear charts so that anyone can understand them at a glance.

In the modern world, companies and organizations cannot afford to rely on gut feelings or luck anymore. Data analysis is incredibly important because it replaces guesswork with solid proof. It helps businesses understand what their customers actually want, shows them how to stop wasting money, and allows them to predict future market shifts instead of just reacting to them when it is too late. Basically, it gives organizations a clear map to navigate a very competitive digital landscape.

You can see this tool at work across almost every industry today. In healthcare, hospitals analyze patient records and real-time vitals to predict dangerous conditions hours before they physically show up. In e-commerce, platforms like Amazon or Netflix track your browsing history to recommend products tailored exactly to your taste, while automatically adjusting prices based on current demand. Even in sports, professional teams use wearable sensors and cameras to track player movements, analyzing the data to build better game tactics and prevent injuries. Ultimately, data analysis is all about turning chaotic information into a clear plan to solve real-world problems.

In [ ]:
#Exercise 2: Dataset Loading and Initial Analysis

import pandas as pd

sleep_path = "Time Americans Spend Sleeping.csv"
mental_health_path = "Mental health Depression Disorder Data.csv"
credit_path = "crx.csv"

df_sleep = pd.read_csv(sleep_path)

print("How Much Sleep Do Americans Really Get? (First 5 Rows)")
display(df_sleep.head())

print("\n[Dataset Description]")
print(f"Dimensions: {df_sleep.shape[0]} rows and {df_sleep.shape[1]} columns.")
print("Columns present:", list(df_sleep.columns))
print("Summary : This dataset details the average daily sleeping habits of Americans. It breaks down sleep duration metrics by demographic variables such as age group, sex, specific daily activities, and whether the data points represent weekdays or weekends.")


df_mental = pd.read_csv(mental_health_path)

print("\nGlobal Trends in Mental Health Disorder (First 5 Rows)")
display(df_mental.head())

print("\n[Dataset Description]")
print(f"Dimensions: {df_mental.shape[0]} rows and {df_mental.shape[1]} columns.")
print("Columns present:", list(df_mental.columns))
print("Summary : An epidemiological dataset mapping the historical prevalence rates of distinct mental health and substance abuse disorders (e.g., depression, anxiety, bipolar disorder) indexed across different countries, regions, and recorded years.")


df_credit = pd.read_csv(credit_path)

print("\n--- Credit Card Approvals (First 5 Rows) ---")
display(df_credit.head())

print("\n[Dataset Description]")
print(f"Dimensions: {df_credit.shape[0]} rows and {df_credit.shape[1]} columns.")
print("Summary : Originating from the UCI Machine Learning Repository, this contains structural applications for credit cards. To preserve consumer confidentiality, all explicit feature labels (e.g., Age, Debt, Income, Credit Score, Approval Status) are masked as anonymized/symbolic variables.")

How Much Sleep Do Americans Really Get? (First 5 Rows)

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

[Dataset Description]
Dimensions: 945 rows and 9 columns.
Columns present: ['index', 'Year', 'Period', 'Avg hrs per day sleeping', 'Standard Error', 'Type of Days', 'Age Group', 'Activity', 'Sex']
Summary : This dataset details the average daily sleeping habits of Americans. It breaks down sleep duration metrics by demographic variables such as age group, sex, specific daily activities, and whether the data points represent weekdays or weekends.

Global Trends in Mental Health Disorder (First 5 Rows)

C:\Users\ierri\AppData\Local\Temp\ipykernel_27876\3417558203.py:20: DtypeWarning: Columns (0: Bipolar disorder (%), 1: Eating disorders (%)) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mental = pd.read_csv(mental_health_path)

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

[Dataset Description]
Dimensions: 108553 rows and 11 columns.
Columns present: ['index', 'Entity', 'Code', 'Year', 'Schizophrenia (%)', 'Bipolar disorder (%)', 'Eating disorders (%)', 'Anxiety disorders (%)', 'Drug use disorders (%)', 'Depression (%)', 'Alcohol use disorders (%)']
Summary : An epidemiological dataset mapping the historical prevalence rates of distinct mental health and substance abuse disorders (e.g., depression, anxiety, bipolar disorder) indexed across different countries, regions, and recorded years.

--- Credit Card Approvals (First 5 Rows) ---

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

[Dataset Description]
Dimensions: 689 rows and 16 columns.
Summary: Originating from the UCI Machine Learning Repository, this contains structural applications for credit cards. To preserve consumer confidentiality, all explicit feature labels (e.g., Age, Debt, Income, Credit Score, Approval Status) are masked as anonymized/symbolic variables.

Exercise 3: Identifying Data Types

How Much Sleep Do Americans Really Get ?

Quantitative : Year, Avg hrs per day sleeping, Standard Error

Qualitative : Period, Type of Days, Age Group, Sex

Global Trends in Mental Health Disorder

Quantitative : Year, Schizophrenia (%), Bipolar disorder (%), Eating disorders (%), Anxiety disorders (%), Drug use disorders (%), Depression (%), Alcohol use (%)

Qualitative : Entity, Code

Credit Card Approvals

Quantitative : A2, A3, A8, A11, A14, A15

Qualitative : A1, A4, A5, A6, A7, A9, A10, A12, A13, A16

In [ ]:
#Exercise 4: Exploring Data Types

import pandas as pd

df = pd.read_csv("Iris.csv")

print("Iris Dataset (First 5 Rows)")
display(df.head())

print("\nDataset Information")
df.info()

Id : Qualitative

SepalLengthCm : Quantitative

SepalWidthCm : Quantitative

PetalLengthCm : Quantitative

PetalWidthCm : Quantitative

Species : Qualitative

Exercise 5: Basic Observation Skills in Data Analysis

Trend Analysis

Columns: Year and Avg hrs per day sleeping

Explanation: By tracking Avg hrs per day sleeping across the chronological timeline of Year, you can determine whether Americans are gaining or losing sleep over time, identifying long-term public health behaviors.

Group Comparison Analysis

Columns: Sex, Age Group, and Avg hrs per day sleeping

Explanation: This allows you to compare average sleep durations between different demographic groups (e.g., Men vs. Women, or Young Adults vs. Seniors) to pinpoint which segments of the population are most sleep-deprived.

Contextual / Day-Type Analysis

Columns: Type of Days (or Period) and Avg hrs per day sleeping

Explanation: This helps analyze the difference in sleeping habits on weekdays versus weekends/holidays, revealing how work-life schedules impact rest patterns.

Exercise 6: Identifying Data Types

A company’s financial reports stored in an Excel file: Structured data

Photographs uploaded to a social media platform: Unstructured data

A collection of news articles on a website: Unstructured data

Inventory data in a relational database: Structured data

Recorded interviews from a market research study: Unstructured data

Exercise 7: Transformation Exercise

1. A series of blog posts about travel experiences

Proposed Method: Apply Natural Language Processing (NLP), specifically Named Entity Recognition (NER) and Sentiment Analysis.

Resulting Structure: A tabular database (Excel/SQL) with columns like: Post_ID, Destination_Country, City, Travel_Duration_Days, Key_Activities, and Sentiment_Score (positive/negative experience rating).

Reasoning: Blog posts contain free-form storytelling. By extracting specific entities (places, times) and assigning a quantitative value to the mood (sentiment), you transform essays into searchable, filterable data rows.

2. Audio recordings of customer service calls

Proposed Method: Implement a two-step pipeline using Speech-to-Text Transcription models followed by Text Mining/Classification algorithms.

Resulting Structure: A structured table with columns like: Call_ID, Timestamp, Call_Duration, Customer_Issue_Category (e.g., billing, technical support), Resolution_Status (Yes/No), and Agent_ID.

Reasoning: Audio files cannot be easily searched or queried directly. Converting them to digital text allows machine learning models to instantly categorize the main reason for the call and quantify customer satisfaction metrics.

3. Handwritten notes from a brainstorming session

Proposed Method: Use Intelligent Character Recognition (ICR) or Optical Character Recognition (OCR) software tailored for handwriting, followed by tag/keyword grouping.

Resulting Structure: A structured spreadsheet or Kanban dataset with columns like: Idea_ID, Core_Theme, Suggested_Action_Item, Assigned_To, and Priority_Level.

Reasoning: Handwritten notes are highly chaotic and physically confined. Digitizing the text with OCR and sorting them by functional tags transforms casual sketches into an actionable project management database.

4. A video tutorial on cooking

Proposed Method: Utilize Video-to-Text Translation (extracting the voice track transcript) combined with Computer Vision (Object Detection) to detect visual milestones.

Resulting Structure: A highly structured recipe profile consisting of two tables:

    Ingredients Table: Ingredient_Name, Quantity, Unit.

    Steps Table: Step_Number, Action/Technique (e.g., chop, boil), Target_Temperature, Duration_Minutes.

Reasoning: A video is a dense stream of continuous audio-visual information. Breaking it down into timestamps, distinct ingredients, and numerical steps turns a visual guide into an organized relational dataset.

In [1]:
#Exercise 8 : Import a file from Kaggle

import pandas as pd

df_train = pd.read_csv("train.csv")

print("First 5 Rows of the Train Dataset")
df_train.head()

First 5 Rows of the Train Dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#Exercise 9 : Export a dataframe to excel format and JSON format.

import pandas as pd

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London']
}
df = pd.DataFrame(data)
print("--- Created DataFrame ---")
print(df)

df.to_excel('simple_dataframe.xlsx', index=False)
print("\nDataFrame successfully exported to 'simple_dataframe.xlsx'")


df.to_json('simple_dataframe.json', orient='records', indent=4)
print("DataFrame successfully exported to 'simple_dataframe.json'")

--- Created DataFrame ---
    Name  Age      City
0   John   28  New York
1   Anna   34     Paris
2  Peter   29    Berlin
3  Linda   32    London

ModuleNotFoundError: No module named 'openpyxl'

In [ ]:
#Exercise 10: Reading JSON Data

import pandas as pd

df_json = pd.read_json("posts.json")

print("First 5 Rows of my JSON")
df_json.head()

Les 5 premières entrées de mon JSON

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...